string DLG_TEXT_RUM [333] = {
	"Ah, capisco... Altre notizie?",
	"Grazie. Ma con tutto il rispetto... no.",
	"Cordiali saluti.",
	"Ah, capisco... Che altre novitР В° ci sono in cittР В°?",
	"Grazie. Ma con tutto il rispetto... no.",
	"Cordiali saluti.",
	" Ecco cosa sta succedendo...",
	" Questa potrebbe divertirti.",
	" E tu, capitano, hai delle notizie per la nostra colonia?",
	"Racconti cose interessanti, ",
	"Dimmi di piРЎвЂ°...",
	"Molto interessante! Oh, volevo chiederti un'altra cosa.",
	"Posso farti un'altra domanda?",
	"Nel mondo intorno a noi possono succedere tante cose. Temo di non avere novitР В°. ",
	"Vado di fretta, sarР В° per un'altra volta.",
	" Raramente succede qualcosa qui, ma se dovesse accadere, ne parlerebbero tutti.",
	" Quindi nessuna notizia al momento, ma forse il capitano della ",
	" sa qualcosa?",
	"Allora perchР в„– non mi racconti?",
	"Non sai niente! D'accordo, volevo chiederti un'altra cosa.",
	"Dici di non saperlo. D'accordo, allora dimmi...",
	"Beh, non mi sei stato",
	" molto utile ",
	" ma magari sai qualcos'altro?",
	"Non credo di sapere qualcosa che possa interessarti.",
	"Ti dirРЎвЂљ qualcosa con piacere, ma magari un'altra volta.",
	"Purtroppo non so nient'altro e ora consentimi di andarmene.",
	"Mi hai stancato con le tue richieste. Scusami, ma ho altro da fare.",
	"Grazie. Ma con tutto il rispetto... no.",
	"Cordiali saluti.",
	"Beh, hic! ",
	"Questo rum Р С‘ molto buono! ",
	"Giiiusto... ",
	"Per questo berrei un altro bicchierino.",
	"Molto bene. Facciamo un altro giro.",
	"Grazie, ma devo andarmene.",
	"Uh, questo rum ti dР В° la carica. Ma ora devo andare. Salute.",
	"Immagina: me ne stavo seduto qui, senza dare fastidio a nessuno, quando all'improvviso quell'Avery mi salta addosso e mi dР В° un pugno in faccia, poi dice 'Devi dei soldi all'usuraio?!' E poi dice di essersi sbagliato. Lui si sarР В° anche sbagliato, ma io ho perso un dente! Eh? Cosa dici? E non ci crederai, ma dopo una settimana, mi fa ancora male. Che dolore! Magari starei meglio con un boccale di birra...?",
	"Beh, certo...",
	"C'era un tizio seduto accanto a me, circa cinque giorni fa, piРЎвЂ° o meno dove sei tu adesso. Si chiamava, aspetta... John Avery. Mi ha detto di avere ingannato l'usuraio locale, eh eh. Ben gli sta a quel maledetto succhiasangue tutto gonfio di denaro, mentre un uomo onesto non ha niente da mettere sotto i denti...",
	"Eh giР В°, gli usurai sono brutta gente.",
	"C'Р С‘ stata una bella rissa qui, tre giorni fa! John Avery ha attaccato un baro. Devo dire che quel tizio Р С‘ molto abile con la spada: vuuum, vuuum e il baro Р С‘ morto! Tutti hanno iniziato a gridare, ma John Р С‘ un tipo perbene: ha pagato da bere a tutti. Lo rispetto molto!",
	"Ah, davvero? Carino...",
	" SР С�, ma non ricordo altro",
	" E ora devo tornare ai miei affari.",
	"Ti ho giР В° detto che non ho tempo per le chiacchiere!",
	"Sono una persona impegnata e non ho tempo per i pettegolezzi!",
	"Molto interessante! Ma ora torniamo ai nostri affari",
	"Grazie, ci sarebbe un'altra cosa",
	"Maledizione! Sei un bravo bugiardo. Ma ho un'altra domanda.",
	"Quindi non sprechiamo altro tempo prezioso e torniamo ai nostri affari",
	" Un'ultima cosa, poi ti lascio andare.",
	"Hai ragione, il tempo Р С‘ denaro.",
	"Pensi solo al tuo tornaconto. Dai, rilassati.",
	"Ti prego di scusarmi. Torniamo ai nostri affari,",
	"A presto, vecchio beone.",
	"I miei piРЎвЂ° cordiali saluti. ",
	"Р Р‹Caramba! Fermo, non muovere un muscolo. Torno subito.",
	"Р пїЅ stato bello vederti, ",
	"! Stammi bene!",
	"Salpa!",
	"Arrivederci, mio buon uomo.",
	"Ehi! Cosa nascondi lР С�? Rum? No?! Allora vado a farmi una bevuta.",
	"Scusami, ho affari urgenti in cittР В°.",
	"Oh. Bene, ci rincontreremo.",
	"Devo andare. Arrivederci, ",
	"Non rispondermi! Non ho il tempo per discutere con te!",
	"Dovrei andare a controllare sulla nave. Solo Dio sa quello che succede quando non ci sono. Arrivederci, ",
	"Ehi amico, stai bene? Sono io, ",
	"! Ok, dormici sopra. TornerРЎвЂљ piРЎвЂ° tardi.",
	"Temo che il tuo fegato ti ucciderР В° prima di me...",
	"Conta le tue piastre, vecchia volpe! TornerРЎвЂљ piРЎвЂ° tardi.",
	"Р пїЅ stato bello vederti, ",
	"Molto interessante! Oh, volevo chiederti un'altra cosa.",
	"Posso farti un'altra domanda?",
	"Grazie. Ma con tutto il rispetto... no.",
	"Arrivederci",
	"Le informazioni costano. Per sole 1000 monete d'oro ti dirРЎвЂљ tutto quello che so.",
	"Accidenti, non me lo ricordo... Ma forse 1000 monete mi rinfrescheranno la memoria.",
	"Sono pronto a dirti tutto quello che so, ma non gratis: voglio 1000 monete, non una di meno.",
	"Non ho niente da aggiungere. E ora scusami, gli affari non aspettano.",
	"Pagare per dei pettegolezzi? No grazie, vai a dirlo a qualcun altro.",
	"Per quella somma posso scoprire tutto da me.",
	"Parliamo di qualcos'altro.",
	"Ti pagherРЎвЂљ se le tue informazioni si riveleranno utili.",
	"Ti pagherРЎвЂљ, ma solo se mi dirai qualcosa di molto importante.",
	"Non ho abbastanza soldi.",
	"Di recente, diverse navi sono scomparse; il fatto strano Р С‘ che spariscono solo trabaccoli e sloop. Pare che un brigantino sia apparso nelle acque di Cumana, perciРЎвЂљ fai attenzione!",
	"Solo trabaccoli, dici? Molto interessante. E sai qualcos'altro?",
	"Non pagherРЎвЂљ per delle chiacchiere, arrivederci.",
	"Le tue informazioni non valgono un soldo bucato: non ti darРЎвЂљ niente.",
	"Grazie, ecco il tuo oro. Ricordi qualcos'altro?",
	"Bene, meriti i tuoi soldi: ecco qui. C'Р С‘ dell'altro?",
	"Non fraintendermi, ho una famiglia da sfamare.",
	"Parliamo di qualcos'altro.",
	"Grazie. Ma con tutto il rispetto... no.",
	"Arrivederci",
	"Arrivederci.",
	"SР С�, interessante. Ho un'altra domanda...",
	"Oh, volevo chiederti un'altra cosa.",
	"Addio, speculatore.",
	"Arrivederci, amico.",
	"Non c'Р С‘ niente di cui parlare, ti ho detto tutto quello che so.",
	"Non ho sentito altro, spiacente...",
	"Capisco. Beh, allora arrivederci.",
	"Capisco. Beh, a presto.",
	"SР С�, interessante. Ho un'altra domanda...",
	"Oh, volevo chiederti un'altra cosa.",
	"Addio, speculatore.",
	"Arrivederci, amico.",
	"Non c'Р С‘ niente di cui parlare, ti ho detto tutto quello che so.",
	"Non ho sentito altro, spiacente...",
	"Capisco. Beh, allora arrivederci.",
	"Capisco. Beh, a presto.",
	"Ho capito...",
	"SР С�, Р С‘ chiaro.",
	"Non c'Р С‘ niente di cui parlare, ti ho detto tutto quello che so.",
	"Non ho saputo altro, mi dispiace.",
	"Spiacente, ti ho giР В° detto tutto quello che so.",
	"Non ho saputo altro, mi dispiace.",
	"Ho capito.",
	"Arrivederci.",
	"Finanze? Mmm, parla: ti ascolto.",
	"Le questioni finanziarie sono sempre interessanti. Parla, ti ascolto.",
	"D'accordo, parliamo di finanze.",
	"Sei sicuro di chiedere alla persona giusta, ",
	"? Mi chiamo ",
	". Come posso aiutarti?",
	"Mi hai chiesto delle finanze, ",
	"?! Mi chiamo ",
	". Cosa vuoi?",
	"Ti ascolto, ",
	"? Desideravi qualcosa? Oh, perdonami. Mi chiamo ",
	"L'usuraio mi ha mandato a riscuotere i suoi soldi: fuori la grana!",
	"C'Р С‘ una questione delicata riguardo al tuo debito, ",
	"Ho portato il tuo credito.",
	"Uh, forse mi sbagliavo. Non ho alcuna domanda finanziaria per te.",
	"Scusa, non ho alcuna domanda finanziaria per te.",
	"SР С�, esattamente. Stavo proprio per restituirglieli.",
	"Ah, molto bene. Allora devi darmi ",
	"Eccellente, ora prendili e riportali da te!",
	"No! Non ti darРЎвЂљ niente! Se insisti, chiamo le guardie.",
	"In ogni caso, devi darmi ",
	". Altrimenti dovremo parlarne in un altro modo.",
	"Р пїЅ proprio cosР С�!",
	"Purtroppo, non ho abbastanza soldi.",
	"In ogni caso, devi darmi ",
	". Altrimenti dovremo parlarne in un altro modo.",
	"E quanto hai?",
	"Ecco l'intera somma.",
	"Grazie per la cooperazione!",
	"Hai 30 giorni per tornare dal committente e restituirgli il denaro.",
	"Mi fa piacere che abbiamo raggiunto un accordo.",
	"Bah, vai al diavolo!",
	"Hai 30 giorni per tornare dal committente e riferirgli del fallimento della missione.",
	"Guardie! Dei fuorilegge mi attaccano!",
	"Silenzio!",
	"Hai 30 giorni per tornare dal committente e riferirgli del fallimento della missione.",
	"Solo ",
	" monete d'oro.",
	"No, mi serve l'intera somma!",
	"Dammi quello che hai, il resto ce lo metto di tasca mia. Oggi mi sento generoso.",
	"Sei molto gentile! Grazie mille.",
	"Oh, perchР в„– mi caccio sempre in queste situazioni?",
	"Hai 30 giorni per tornare dal committente e restituirgli il denaro.",
	"Molto bene, accetto il tuo oro. Ma non ce l'hai fatta entro i termini di consegna stabiliti, quindi mi vedo costretto a ridurre il tuo compenso del ",
	"%. Mi spiace, ma su questo non si discute. Tieni, prendi...",
	"Grazie!",
	"Eccellente! L'aspettavo da tempo. Ecco la tua ricompensa.",
	"Grazie!",
	"Eccellente! Ma dove sono tutti i forzieri con l'oro?",
	"Accetteresti l'oro senza i forzieri?",
	"TornerРЎвЂљ piРЎвЂ° tardi.",
	"No! Solo nei forzieri!",
	"Peccato. I topi li hanno rovinati.",
	"Beh, una somma di, diciamo... ",
	" potrebbe coprire il costo dei forzieri?",
	"SР С�, mi pare accettabile.",
	"Allora siamo d'accordo!",
	"Per me Р С‘ troppo.",
	"Р пїЅ un piacere fare affari con te!",
	"Grazie!",
	"Molto bene. Ho un pacchetto pronto per te, che devi consegnare direttamente a una persona nota. Prendi.   \nNon avvicinarti piРЎвЂ° a me e non parlarmi per non destare sospetti. Fai attenzione.",
	"Mmm, perfetto. Ti darРЎвЂљ il pacco e ricorda che devi consegnarlo direttamente nelle mani della persona specificata.   \nOra arrivederci e non avvicinarti a me: Р С‘ troppo pericoloso.",
	"Ho capito. Arrivederci.",
	"Arrivederci e buona fortuna.",
	"Ehi, hai trovato la polvere di mummia che ti avevo chiesto di cercare?",
	"No, non ancora. Senti, pare che i mercanti nelle strade ce l'abbiano, ma per qualche motivo non vogliono venderla.",
	"No, non ancora. ContinuerРЎвЂљ a cercarla.",
	"Ehi, hai trovato la polvere di mummia che ti avevo chiesto di cercare?",
	"SР С�, l'ho trovata. Quanto sei disposto a pagarmela?",
	"Niente. Ma conosco qualcuno pronto a comprarla.",
	"Beh, contavo di essere pagato immediatamente.",
	"Vedrai che non ci rimetterai. Ascolta attentamente.",
	"Nella cittР В° di Basse-Terre in Guadalupa vive uno strano personaggio chiamato Ascold.",
	"Strano nome...",
	"Lo conosco, una volta gli ho parlato: Р С‘ un tizio impudente...",
	"Come?! L'hai incontrato?",
	"Oh sР С�, mi ha cacciato fuori da casa sua come se fossi un furfantello qualsiasi!",
	"Ascold Р С‘ un po' rude, ma Р С‘ una persona buona e onesta. Si dice che sia un moscovita: il suo popolo vive a nord nel Vecchio mondo, dove c'Р С‘ la neve tutto l'anno e dove non ci sono altro che foreste e orsi. Per questo ha un carattere rigido e una forza nelle mani pari a quella di quattro giovanotti.",
	"Non so come e quando sia arrivato qui e non so nemmeno per quale motivo sia venuto.",
	"Ma si fida di me, perchР в„– faccio affari con lui.",
	"PerciРЎвЂљ vai da lui, presentati, digli che ti mando io e sarР В° tutto a posto. ComprerР В° da te questa robaccia perchР в„– gli Р С‘ stato ordinato.",
	"E tu cosa ci guadagni?",
	"Non preoccuparti per me, tratterrРЎвЂљ la mia commissione dalla nostra cassa comune.",
	"Capisco. Magari farРЎвЂљ un salto da questo Ascold quando ne avrРЎвЂљ l'occasione.",
	"Hanno forse nominato l'Inquisizione?",
	"SР С�, proprio cosР С�.",
	"Beh, che ti aspettavi? Ti dico una cosa, amico: loro hanno la polvere. Non tutti, ovviamente, ma qualcuno ce l'ha, quindi devi fargli pressione e ottenere quello che ti serve.",
	"Bene, allora grazie per l'aiuto.",
	"Diamo un'occhiata a questo barattolo. Eh no. Guarda: ci sono delle strane scritte, probabilmente si tratta di stregoneria. Ti consiglio di portarlo in chiesa, lР С� decideranno cosa farne.",
	"Grazie per il consiglio.",
	"LР С� sul tavolo ci sono degli attrezzi: una fiamma ossidrica, una sega, cesoie per il metallo e altro. Prendili e aprilo da te, non voglio denaro in cambio.",
	"Grazie, ",
	"Hai fatto la cosa giusta, figliolo. Non sappiamo cosa contenga, ma a quanto pare domani dovremo riconsacrare la chiesa.",
	"Non voglio chiederti dove l'hai trovato. Nel nome del Signore, ti assolvo da tutti i tuoi peccati! Vai in pace.",
	"Grazie, padre.",
	"Rapina in pieno giorno! Che diavolo succede? Resisti, amico...",
	"Ehi, perchР в„– bazzichi da queste parti? Non starai pensando di derubarmi? In questo caso, per te Р С‘ la fine!",
	"Aspetta, dove vuoi andare? Oh, cosР С� sei un ladro! Considerati spacciato, amico...",
	"Maledetto! Galoppino! Vagabondo! ",
	"Р Р‹Ay Caramba!",
	"",
	"Oh capitano, non Р С‘ successo, ma accade da molto tempo ormai. Noi mercanti del mare dei Caraibi siamo sull'orlo del fallimento e tutto a causa di quella maledetta Blue Bird!",
	"Blue Bird?",
	"SР С�, la xebec del diavolo, l'unica nave di quel tipo, nessuno le sfugge in mare. Affonda solo le navi dei mercanti, mentre non attacca le grandi carovane protette da imbarcazioni militari.",
	"Allora perchР в„– dici che i mercanti sono rovinati? Dopo tutto, le merci continuano ad arrivare con queste carovane.",
	"SР С�, Р С‘ vero, ma il fatturato non Р С‘ piРЎвЂ° proficuo in questa situazione. Р пїЅ piРЎвЂ° conveniente avere la propria sloop o fluyt, comprare le merci nel Vecchio mondo e trasportarle qui da soli, questo sР С� che Р С‘ commercio!   \nMa quando devi comprare le merci dai trasportatori, non si puРЎвЂљ piРЎвЂ° parlare di profitto, ma di mera sopravvivenza.",
	"Capisco. Quindi solo le vostre navi vengono affondate dalla xebec...",
	"Esatto. Quasi tutti i mercanti hanno giР В° perso le loro navi, maledetta Blue Bird!",
	"GiР В°, dev'essere un problema per voi. Allora, che cosa volete da me?",
	"Vogliamo che tu distrugga quel pipistrello dalle ali grigie, maledizione!",
	"E io cosa ci guadagno?",
	"FarРЎвЂљ una colletta tra i miei colleghi e racimolerРЎвЂљ una ghiotta ricompensa. Ti prometto cinquantamila piastre. La xebec del diavolo deve finire in fondo al mare!",
	"Non muoverРЎвЂљ nemmeno un dito per questa somma, amico. Cerca un altro allocco!",
	"SР С�, la somma Р С‘ interessante, accetto l'incarico. Quali sono i termini di completamento?",
	"Non avrai limiti di tempo. Capisco perfettamente che sarР В° difficile, maledizione! A dire la veritР В°, abbiamo giР В° cercato di assoldare dei sicari: volevamo assassinare il capitano, ma non abbiamo ottenuto risultati.",
	"Davvero? Puoi parlarmene piРЎвЂ° dettagliatamente?",
	"Beh, ognuno di noi ha messo del denaro per assumere qualcuno che trovasse il capitano della xebec tra i pirati. Ma non ha funzionato: il nostro sicario ha perlustrato i Caraibi per sei mesi, ma non ha trovato nulla. Solo il diavolo sa dove hanno la loro base e come vendono il bottino.",
	"D'accordo, amico, Р С‘ giР В° qualcosa. E ora ascolta le mie condizioni.",
	"Ascolto attentamente, ",
	"Il patto Р С‘ tra te e me: racimola il denaro come vuoi, ma non dire una parola a nessuno riguardo il mio coinvolgimento. E c'Р С‘ un'altra cosa: hai detto che QUASI tutti i mercanti hanno perso le loro navi. Cosa intendi dire?",
	"Un usuraio ha ancora una fluyt, ma Р С‘ stato fortunato: non ha mai incontrato la xebec. Р пїЅ la nostra unica speranza di stabilirci definitivamente qui, tutti i nostri uomini gli sono debitori. Se non ci aiutasse in questo momento difficile, per noi sarebbe la fine. Non ha mai rifiutato le nostre richieste di prestiti!",
	"Capisco. Praticamente Р С‘ un santo! Allora, come si chiama?",
	"Pascal Vousier. Gestisce un negozio alle Bermuda, nell'insediamento dei pirati. Allora, accetti questo incarico?",
	"E tu accetti le mie condizioni di riservatezza?",
	"Naturalmente!",
	"Allora accetto. InizierРЎвЂљ le ricerche oggi stesso e spero di concluderle presto.",
	"Oh, vorrei che fosse cosР С�! Bene, puoi iniziare. Spero che tutto vada come dici tu.",
	"AndrР В° tutto bene, vedrai!",
	"Beh, peccato. Magari cercheremo un altro 'allocco' altrove.",
	"Mmm...",
	"Ottime notizie! Finalmente possiamo commerciare liberamente. Vuoi subito il tuo denaro?",
	"SР С�, sarebbe meglio.",
	"Mmm, aspetta. Per quanto ne so, hai catturato la xebec ma non l'hai affondata: ora appartiene a te.",
	"SР С�, Р С‘ cosР С�. Che problema c'Р С‘?",
	"Nessun problema, ecco la tua ricompensa.",
	"Grazie, allora siamo a posto. Ti faccio tanti auguri. A proposito, vuoi sapere chi c'era dietro a tutto questo?",
	"Beh, sarebbe interessante...",
	"Era quel mercante 'santo' nel mare dei Caraibi: Pascal Vousier.",
	"Impossibile!",
	"Invece Р С‘ possibile. Purtroppo non ho prove, ma pensa a chi ti presta il tuo stesso denaro.",
	"Beh, bisognerebbe verificare. Grazie per il tuo lavoro e per le informazioni.",
	"Di niente, hai pagato tutto tu. Arrivederci.",
	"Il problema Р С‘ che quella maledetta nave ora Р С‘ in mano tua e, tra parentesi, anche tu sei un pirata, quindi chi ti impedirР В° di assaltare i mercanti come il capitano precedente?",
	"Beh, la tua Р С‘ una domanda interessante. A ogni modo, ho compiuto la missione!",
	"No, non l'hai fatto: dovevi affondare la Blue Bird, non catturarla.",
	"Ah, dunque Р С‘ questa la tua risposta! Bene, capisco. Ti auguro ogni bene, manda i miei piРЎвЂ° cari saluti ai tuoi colleghi.",
	"Lo farРЎвЂљ senz'altro! Arrivederci, e la prossima volta mantieni completamente la parola data.",
	"Certamente. Ma ci rivedremo...",
	"Р пїЅ un peccato. Beh, non sei il primo che accetta questo incarico e fallisce. Dovremo rassegnarci...",
	"Spero che, a tempo debito, le cose si sistemeranno.",
	"Р пїЅ vero. Viviamo per cose vane e crediamo che la terra ruoti intorno a noi, Invece veniamo dalla terra e alla terra torneremo.   \nEh, oggi sono di umore poetico.",
	"A volte succede. Bene, arrivederci.",
	"Oh, bastardo! Quindi le nostre paure erano fondate!",
	"Ti lascerei in pace, se tu non mi imbrogliassi!",
	"Ah, dannazione! Guardie, arrestatelo! Non andrai lontano, bastardo...",
	"Ti conveniva darmi i miei soldi, furbone. Continuiamo il trattamento...",
	"Maledetto bastardo! Mi pento di averti ingaggiato! Prima della tua venuta, la Blue Bird non ci aveva mai dato cosР С� tanti problemi!",
	"Amici miei, Р С‘ tutta colpa vostra: avreste dovuto attenervi al nostro accordo.",
	"Come sarebbe a dire? Noi l'abbiamo rispettato, sei stato tu a infrangerlo non affondando la xebec!",
	"Mon cher, non c'Р С‘ bisogno di gridare, ti fa male alle corde vocali. E se all'improvviso non riuscissi piРЎвЂ° a parlare? Comunque, sono pronto a parlare con te, se manterrai la calma.",
	"D'accordo, ma la calma non c'entra nulla. Il problema Р С‘ che sei stato tu, non noi, a infrangere i termini dell'accordo!",
	"Eh! Voi mercanti siete maestri dei cavilli, conosco i vostri trucchi. Basta una virgola in piРЎвЂ° per cambiare il significato di un testo.",
	"Cosa c'entrano le virgole? Avevamo un accordo verbale.",
	"Beh, era una metafora. Il fatto Р С‘ che hai avuto la possibilitР В° di tenere il denaro che mi avevi promesso e l'hai sfruttata. Io sono un pirata, non ho tempo di analizzare le ambiguitР В° delle tue condizioni.",
	"Quali condizioni?",
	"Le condizioni del nostro accordo. La Blue Bird vi dava dei problemi e io li ho risolti. Se mi avessi dato i miei soldi, non ti avrei toccato nemmeno con un dito. Quindi tutti i tuoi problemi te li sei causato da solo, per cosР С� dire.",
	"D'accordo, prendi i cinquantamila e vattene da qui!",
	"Non cosР С� in fretta, mon cher. Il fatto Р С‘ che ho dovuto sostenere delle spese aggiuntive, per metterti sulla strada giusta, per non parlare dello stress che ho subito. Quindi la somma Р С‘ aumentata.",
	"E qual Р С‘ la nuova somma? Dimmi.",
	"Quattro volte la cifra iniziale. Duecentomila e ti lascio in pace, altrimenti prima ti rovino e poi ti uccido. AmmazzerРЎвЂљ prima la tua famiglia e poi te...",
	"Oh, sei un diavolo!",
	"SР С�, un diavolo infuriato...",
	"Molto bene. Ecco i tuoi soldi. E ora sparisci! Lasciaci in pace!",
	"Senz'altro. Ora che mi hai pagato completamente, la Blue Bird non vi infastidirР В° piРЎвЂ°. Addio e auguri per i tuoi affari.",
	"Giusto. Puoi avere un milione di piastre entro un minuto da quando avrРЎвЂљ l'autorizzazione.",
	"Te l'ho giР В° detto, ",
	", ho un deposito e sto aspettando l'autorizzazione per trasferirlo.",
	"Non preoccuparti: ho un deposito e sto aspettando l'autorizzazione per trasferirlo.",
	"Mmm, mi pare che questo deposito ti interessi un po' troppo. La mia reputazione Р С‘ senza macchia, quindi posso solo ripetere quanto ho giР В° detto: ho un deposito a tuo nome e riceverai i soldi non appena avrРЎвЂљ l'autorizzazione al trasferimento.",
	"Capisco. Beh, perfetto. Ho saputo quello che volevo.",
	"Argh. Ok, ho capito.",
	"Anch'io, non preoccuparti.",
	"Capisco... Grazie, ",
	"SР С� sР С�, ho ricevuto il permesso di effettuare l'operazione. Riceverai ",
	"Ah, molto bene.",
	"Magari vuoi far fruttare questo denaro? Sono al tuo servizio, la mia reputazione...",
	"Ho capito, grazie. Ci penserРЎвЂљ.",
	"Eccoti, finalmente!",
	"Che succede? PerchР в„– non sei ancora a bordo della corvetta? E dov'Р С‘ il meccanico?",
	"Non so dove si trovi. Mentre salivo sulla San Gabriel, le guardie lo stavano portando via. Pare che sia stato arrestato e solo l'ammiraglio poteva impartire questo ordine.",
	"Р Р‹Ay Caramba! Ora cosa facciamo?",
	"Non possiamo fare a meno del meccanico?",
	"Ci serve Vedeker. Possiamo salire sulla corvetta, ma non potremo liberarla senza Henrik.",
	"Allora dobbiamo andare alla residenza del bucaniere e salvare il meccanico. Purtroppo io non posso farlo: lo sguardo dell'ammiraglio mi dР В° i brividi...",
	"Eh, Р С‘ ovvio... Sali sulla nave, presto tornerР В° con Vedeker. Pare che gli altri membri dell'equipaggio siano giР В° a bordo.",
	"Come desideri, capitano.",
	"Non farti prendere dal panico. AndrР В° tutto bene.",
	"Eccoti, finalmente!",
	"Che succede? PerchР в„– non sei ancora a bordo della corvetta? E dov'Р С‘ il meccanico?",
	"Non so dove si trovi. Quando sono arrivato sulla San Gabriel, le guardie lo stavano portando via. Pare che sia stato arrestato e solo l'ammiraglio poteva impartire questo ordine.",
	"Р Р‹Ay Caramba! Ora cosa facciamo?",
	"Non possiamo fare a meno del meccanico?",
	"Ci serve Vedeker. Possiamo salire sulla corvetta, ma non potremo liberarla senza Henrik.",
	"Allora dobbiamo andare alla residenza del bucaniere e salvare il meccanico. Purtroppo, essendo una donna, non posso aiutarti.",
	"Questo Р С‘ poco ma sicuro. Sali sulla nave, presto tornerР В° con Vedeker. Pare che gli altri membri dell'equipaggio siano giР В° a bordo.",
	"Come desideri, capitano.",
	"Non farti prendere dal panico. AndrР В° tutto bene.",
	"ha accettato di",
	"ha accettato di",
	"ha accettato di",
	"ha accettato di",
};
