string DLG_TEXT_RUM [333] = {
	"Hm, ich verstehe ... Weitere Neuigkeiten?",
	"Vielen Dank. Respektvoll ... nein.",
	"Viel GlСЊck.",
	"Ah, in Ordnung ... Sonst noch etwas Neues in der Stadt?",
	"Vielen Dank. Respektvoll ... nein.",
	"Viel GlСЊck.",
	" Ah, das ist also los ...",
	" Das wird Sie vielleicht amСЊsieren.",
	" Und haben Sie irgendwelche Neuigkeiten von unserer Kolonie, KapitРґn?",
	"Sie erzРґhlen da interessante Sachen, ",
	"ErzРґhlen Sie mir mehr ...",
	"Das ist РґuРЇerst interessant! Oh, ich wollte noch etwas anderes fragen ...",
	"Kann ich eine weitere Frage stellen?",
	"Es kС†nnte so viel bei uns passieren. Leider kann ich nichts Neues berichten. ",
	"Ich bin derzeit in Eile. Reden wir besser ein Andermal darСЊber.",
	" Hier ist selten etwas los. Wenn etwas AuРЇergewС†hnliches passiert wРґre, wСЊrde jeder darСЊber reden.",
	" Nichts Neues im Moment. Aber vielleicht ",
	" hat der KapitРґn etwas zu berichten?",
	"Warum erzРґhlen Sie es mir dann nicht ...",
	"Sie wissen СЊberhaupt nichts! In Ordnung, ich wollte noch etwas fragen ...",
	"Sie wissen es nicht, sagen Sie. In Ordnung, dann erzРґhlen Sie mir ...",
	"Nun, Sie waren",
	" fСЊr mich keine groРЇe Hilfe ",
	", aber vielleicht wissen Sie etwas anderes?",
	"Ich denke nicht, dass ich etwas weiРЇ, das Sie interessieren kС†nnte.",
	"Ich werde Ihnen gerne etwas erzРґhlen, aber besser ein anderes Mal.",
	"Leider weiРЇ ich nichts darСЊber. Kann ich gehen?",
	"Ihre Fragen waren anstrengend. Wenn Sie mich nun entschuldigen, ich habe viel zu tun.",
	"Vielen Dank. Respektvoll ... nein.",
	"Viel GlСЊck.",
	"Nun ... Hicks! ",
	"Heh, dieser Rum ist gut! ",
	"Koo - rrrekt ... ",
	"Darauf trinke ich ein weiteres Glas ...",
	"Nun gut - eine weitere Runde.",
	"Danke, aber ich muss gehen.",
	"Huhh, dieser Rum hat was. Wie dem auch sei, ich muss los. Gehabt Euch wohl.",
	"KС†nnen Sie sich das vorstellen? Ich sitz' hier, stС†re niemanden, als plС†tzlich dieser Avory auf mich zurauscht und mir eine reinhaut! Dann sagt er, 'Schulden Sie dem Mittelsmann Geld?'. Doch dann meint er, es ist'n Fehler gewesen. Er hРґtte sich geirrt - und ich habe einen Zahn verloren! Heh? Was sagt man dazu? Es ist kaum zu glauben, das ist schon 'ne Woche her, tut aber immer noch hС†llisch weh. Was fСЊr Schmerzen! Ein Krug Ale? ...",
	"Nun, natСЊrlich ...",
	"Vor fСЊnf Tagen saРЇ dieser Typ neben mir, genau wie Sie gerade. Sein Name war, lassen Sie mich СЊberlegen ... John Avory. Der Kerl erzРґhlte mir, dass er den hiesigen Wucherer СЊber's Ohr gehauen hat, hehehe. Das wird ihm 'ne Lehre sein, diesem verdammten Blutsauger; hockt auf seinem Geld herum, wРґhrend ein ehrlicher Arbeiter nicht mal genug zum Essen hat ...",
	"Oh ja, diese Wucherer sind ekelhaft.",
	"Vor drei Tagen hatten wir hier einen groРЇartigen Kampf! John Avory hat einen Falschspieler entlarvt. Der Typ ist hervorragend mit der Klinge, das muss man ihm lassen. Wusch, wusch - und der Falschspieler war weg. Die HСЊtte hier hat fС†rmlich gebebt. Aber John ist ein prima Kerl - hat allen in der Schenke einen ausgegeben. Respekt! ",
	"Ach wirklich? Nett ...",
	" Ja. Kann mich an sonst nichts mehr erinnern",
	" Und jetzt muss ich wieder meinen Pflichten nachkommen.",
	"Ich hatte Ihnen bereits gesagt, dass ich keine Zeit fСЊr leeres GeschwРґtz habe!",
	"Ich bin eine beschРґftigte Person, und ich habe keine Zeit zum Tratschen!",
	"Das ist sehr interessant! Aber nun wieder an die Arbeit",
	"Danke, aber da ist noch etwas",
	"Unglaublich! Sie sind ein guter LСЊgner. Aber ich habe eine weitere Frage.",
	"Dann vergeuden wir nicht mehr Ihre kostbare Zeit, sondern gehen wieder an die Arbeit",
	" Noch eine Sache, dann gehe ich.",
	"Sie haben recht - Zeit ist Geld.",
	"Sie denken nur an Ihren eigenen Vorteil. In Ordnung, entspannen.",
	"Entschuldigen Sie bitte. Gehen wir wieder an die Arbeit.",
	"Auf bessere Tage, Sie alter Schwachmat.",
	"Viel GlСЊck, ",
	"РЋCaramba! Hey, keine Bewegung. Ich bin gleich zurСЊck.",
	"SchС†n, Sie gesehen zu haben, ",
	"! Passen Sie auf sich auf!",
	"Leinen los!",
	"Auf Wiedersehen, mein guter Mann.",
	"Hey! Was verstecken Sie da? Rum? Oder? Nun gut, dann werde ich einen trinken.",
	"Entschuldigung. Ich habe dringende GeschРґfte in der Stadt.",
	"Ho. Na, wir treffen uns wieder.",
	"Ich muss gehen. Auf Wiedersehen, ",
	"Keine so frechen Antworten! Ich habe keine Zeit fСЊr Diskussionen mit Ihnen!",
	"Ich sollte mich mal besser um mein Schiff kСЊmmern. Wer weiРЇ, was da vor sich geht, wРґhrend ich weg bin. Auf Wiedersehen, ",
	"Hey, Freund, geht es Ihnen gut? Ich bin's, ",
	"! Okay, pennen Sie weiter. Ich komme spРґter wieder.",
	"Ich fСЊrchte, Ihre Leber wird sich frСЊher bei Ihnen melden als ich ...",
	"ZРґhlen Sie Ihre Piaster, Sie alter Fuchs! Ich komme spРґter wieder.",
	"Gut, Sie gesehen zu haben, ",
	"Das ist РґuРЇerst interessant! Oh, ich wollte noch etwas anderes fragen ...",
	"Kann ich eine weitere Frage stellen?",
	"Vielen Dank. Respektvoll ... nein.",
	"Auf Wiedersehen",
	"Informationen kosten Geld. FСЊr eine bescheidene Summe von 1000 Gold sage ich Ihnen alles, was Sie wissen wollen.",
	"Irgendwie kann ich mich nicht mehr daran erinnern. Aber vielleicht helfen 1000 MСЊnzen meinem GedРґchtnis auf die SprСЊnge.",
	"Ich bin bereit, Ihnen alles zu erzРґhlen, was ich weiРЇ. Aber nicht umsonst - 1000 Gold und nicht weniger.",
	"Dem habe ich nichts hinzuzufСЊgen. Und nun entschuldigen Sie mich bitte, ich habe viel zu tun.",
	"Zahlen fСЊr leeres GeschwРґtz? Nein danke, probieren Sie es bei jemand anderem.",
	"FСЊr so viel Geld finde ich selbst alles heraus.",
	"Reden wir СЊber etwas anderes.",
	"Sie bekommen es, wenn Sie wirklich wertvolle Informationen fСЊr mich haben.",
	"Ich werde zahlen, aber nur wenn Sie etwas wirklich Wichtiges zu berichten haben.",
	"Ich habe nicht so viel Geld.",
	"In letzter Zeit sind viele Schiffe verschwunden, und das Komische dabei ist, dass nur Kurier-Logger und Slupen vermisst werden. Es wird erzРґhlt, dass es eine Brigg im Meer von Cumana gibt ... Also vorsichtig sein!",
	"Nur Kurier-Logger sagen Sie? Sehr interessant ... Gibt es sonst noch etwas von Interesse?",
	"Ich bezahle nichts fСЊr leeres GeschwРґtz. Leben Sie wohl.",
	"Ihre Informationen sind keinen Pfifferling wert - Sie bekommen von mir nichts.",
	"Ich danke Ihnen - hier ist Ihr Gold. KС†nnen Sie sich an sonst noch etwas erinnern?",
	"Gut, Sie haben sich das Geld verdient. Nehmen Sie es. Gibt es sonst noch etwas?",
	"Bitte verstehen Sie mich nicht falsch, aber ich habe eine Familie zu ernРґhren.",
	"Reden wir СЊber etwas anderes.",
	"Vielen Dank. Respektvoll ... nein.",
	"Auf Wiedersehen",
	"Auf Wiedersehen.",
	"Ja, das ist interessant. Ich habe eine weitere Frage ...",
	"Hm, ich wollte noch etwas fragen ...",
	"Leben Sie wohl, Spekulant.",
	"Auf Wiedersehen, mein Freund.",
	"Es gibt sonst nichts. Ich habe Ihnen alles gesagt, was ich weiРЇ.",
	"Ich habe sonst keine weiteren GerСЊchte gehС†rt, tut mir leid ...",
	"Ich verstehe. Dann auf Wiedersehen.",
	"In Ordnung. Passen Sie auf sich auf ...",
	"Ja, das ist interessant. Ich habe eine weitere Frage ...",
	"Hm, ich wollte noch etwas fragen ...",
	"Leben Sie wohl, Spekulant.",
	"Auf Wiedersehen, mein Freund.",
	"Es gibt sonst nichts. Ich habe Ihnen alles gesagt, was ich weiРЇ.",
	"Ich habe sonst keine weiteren GerСЊchte gehС†rt, tut mir leid ...",
	"Ich verstehe. Dann auf Wiedersehen.",
	"In Ordnung. Passen Sie auf sich auf ...",
	"Verstanden ...",
	"Ja, das ist klar.",
	"Es gibt sonst nichts. Ich habe Ihnen alles gesagt, was ich weiРЇ.",
	"Habe sonst nichts gehС†rt, tut mir leid ...",
	"Entschuldigen Sie, aber ich habe Ihnen alles gesagt.",
	"Ich habe sonst keine GerСЊchte gehС†rt, tut mir leid ...",
	"Verstanden.",
	"Dann auf Wiedersehen.",
	"Finanzen? Hm, ich bin ganz Ohr.",
	"Finanzfragen sind immer interessant. Reden Sie, ich bin ganz Ohr.",
	"In Ordnung, reden wir СЊbers Geld.",
	"Sind Sie sicher, dass Sie da die richtige Person fragen, ",
	"? Ich heiРЇe ",
	". Wie kann ich Ihnen helfen?",
	"Sie fragen mich bezСЊglich Finanzen, ",
	"? Ich bin ",
	". Welche GeschРґfte machen Sie denn?",
	"Ich hС†re Ihnen zu, ",
	"? MС†chten Sie etwas? Oh, entschuldigen Sie. Mein Name ist ",
	"Der Wucherer hat mich geschickt, um Schulden einzutreiben! Geld auf den Tisch!",
	"Ich habe da eine heikle Frage bezСЊglich Ihrer Schulden, ",
	"Ich habe Ihren Kredit mitgebracht.",
	"Р”hm, das war vielleicht ein MissverstРґndnis. Ich habe keine Geldsachen mit Ihnen zu tun.",
	"Tut mir leid, ich habe keine Geldfragen fСЊr Sie.",
	"Ja, genau. Ich wollte ihm gerade alles zurСЊckbringen.",
	"Ah, das ist sehr gut! Dann geben Sie mir ",
	"Ausgezeichnet, dann bringen Sie es selbst zurСЊck!",
	"Nein! Ich werde Ihnen gar nichts geben! Und wenn Sie darauf bestehen, werde ich die Wache rufen.",
	"Wie auch immer, geben Sie mir ",
	". Ansonsten mСЊssen wir uns auf eine andere Weise unterhalten.",
	"Das stimmt!",
	"Leider habe ich nicht die komplette Summe.",
	"Wie auch immer, geben Sie mir ",
	". Ansonsten mСЊssen wir uns auf eine andere Weise unterhalten.",
	"Und wie viel haben Sie?",
	"Hier ist die komplette Summe.",
	"Danke fСЊr die Kooperation!",
	"Sie haben 30 Tage Zeit, um sich beim Arbeitgeber zu melden und ihm das Geld zurСЊckzubringen.",
	"Ich bin froh, dass wir eine Р¬bereinkunft erreicht haben.",
	"Pah, vergesst es!",
	"Sie haben 30 Tage Zeit, um sich beim Arbeitgeber bezСЊglich der gescheiterten Mission zu melden.",
	"Wache! Wandale machen hier Р”rger!",
	"Maul halten!",
	"Sie haben 30 Tage Zeit, um sich beim Arbeitgeber bezСЊglich der gescheiterten Mission zu melden.",
	"Nur ",
	" Gold.",
	"Nein, ich brauche die ganze Summe!",
	"Geben Sie mir, was Sie haben. Ich bezahle den Rest. Ich habe heute die Spendierhosen an.",
	"Sie sind sehr nett! Vielen Dank.",
	"Oh, wieso gerate ich denn stРґndig in solche Situationen?",
	"Sie haben 30 Tage Zeit, um sich beim Arbeitgeber zu melden und ihm das Geld zurСЊckzubringen.",
	"Es ist alles bestens, und ich nehme Ihr Gold an. Sie haben das jedoch nicht in der vereinbarten Zeit erledigt. Aus diesem Grund reduziere ich Ihre GebСЊhr um ",
	"%. Tut mir leid, daran gibt es nichts zu rСЊtteln. Bitte nehmen Sie das ...",
	"Danke!",
	"Ausgezeichnet! Ich habe lange darauf gewartet. Hier ist Ihre Belohnung.",
	"Danke!",
	"Ausgezeichnet! Aber wo sind all die Goldtruhen?",
	"WСЊrden Sie das Gold auch ohne die Truhen annehmen?",
	"Ich komme spРґter wieder.",
	"Nein! Nur in Truhen!",
	"Das ist schlecht. Die Ratten haben es verdorben.",
	"Nun, wird die Summe von, sagen wir, ",
	" die Kosten der Truhen decken?",
	"Ja, das ist akzeptabel",
	"So war es vereinbart!",
	"Nur, das ist zu viel fСЊr mich.",
	"Es ist gut, mit Ihnen GeschРґfte zu machen!",
	"Danke!",
	"Nun, in Ordnung. Ich habe hier ein Paket fСЊr Sie, dass Sie jemandem Bekannten liefern mСЊssen, und zwar persС†nlich. Hier, nehmen Sie es.   \nKommen Sie nicht mehr zu mir und sprechen Sie mich nicht an - es kС†nnte verdРґchtig wirken. Seien Sie vorsichtig ...",
	"Hm, perfekt. Ich СЊbergebe Ihnen das Paket. Und denken Sie daran, es muss dem EmpfРґnger persС†nlich СЊberreicht werden.   \nAuf Wiedersehen, und halten Sie sich von mir fern, es kС†nnte sonst gefРґhrlich sein.",
	"In Ordnung. Leben Sie wohl ...",
	"Leben Sie wohl und viel GlСЊck.",
	"Hey, sind Sie inzwischen auf das Mumienpulver gestoРЇen, nach dem ich Sie gebeten habe?",
	"Noch nicht ... HРґnder auf der StraРЇe scheinen es jedoch zu haben, aber aus irgendeinem Grund, vermasseln Sie es ...",
	"Noch nicht ... Aber ich werde weiter danach suchen.",
	"Hey, sind Sie inzwischen auf das Mumienpulver gestoРЇen, nach dem ich Sie gebeten habe?",
	"Ja, ich habe es gefunden. Wie viel werden Sie mir dafСЊr geben?",
	"Nichts. Aber ich kenne jemanden, der es Ihnen abkaufen wird.",
	"Hm, ich hatte damit gerechnet, das Geld sofort zu bekommen.",
	"Ich glaube, Ihnen wird hier nichts entgehen. HС†ren Sie gut zu.",
	"In Guadeloupe, in der Stadt Basse-Terre, lebt ein seltsamer Vogel namens Ascold.",
	"Seltsamer Name ...",
	"Ich kenne ihn, ich hatte mich einmal mit ihm unterhalten. Er ist ein unverschРґmter Typ ...",
	"Was heiРЇt das? Haben Sie einmal sein aufbrausendes Temperament mitbekommen?",
	"In der Tat, er warf mich einfach aus der TСЊr, als ob ich irgendein Bengel wРґre!",
	"Ascold ist ein bisschen grobschlРґchtig, aber ein guter, ehrlicher Mensch. Es wird gemunkelt, er sei ein Moskowiter - ein Volk im Norden der alten Welt, wo es das ganze Jahr СЊber schneit und СЊberall nur WРґlder und BРґren sind. Aus diesem Grund hat er solch einen ernsten Charakter und ist so stark wie vier MРґnner zusammen.",
	"Ich habe wirklich keine Ahnung, wie und wann er hierher kam oder was er vorhat.",
	"Aber er vertraut mir, da ich mit ihm Handel treibe.",
	"Also, besuchen Sie ihn, stellen Sie sich vor und sagen Sie ihm, dass ich Sie geschickt habe - dann ist alles in Ordnung. Er wird Ihnen diesen MСЊll abkaufen, da es seine Bestellung ist.",
	"Und was gewinnen Sie bei der Sache?",
	"Machen Sie sich keine Sorgen um mich, ich behalte die erforderliche Summe der KommissionsgebСЊhr von unserem gemeinsamen Geldfluss.",
	"Ich verstehe. Nun, ich werde vielleicht bei diesem Ascold vorbeischauen, wenn ich die Gelegenheit dazu habe.",
	"Vielleicht, haben sie von der Inquisition gesprochen?",
	"In der Tat ...",
	"Was hatten Sie erwartet? ... Ich sage Ihnen etwas, mein Freund - die haben das Pulver. NatСЊrlich nicht alle, aber irgendeiner auf jeden Fall. Aus diesem Grund muss man mehr Druck auf sie ausСЊben - und dann bekommt man auch das, was man will.",
	"Heh, in Ordnung, danke fСЊr die Hilfe.",
	"Sehen wir uns einmal diese Blechdose an. Р”hm, nein. Sehen Sie doch - sie ist voll mit seltsamen Buchstaben, wahrscheinlich Zauberei. Ich empfehle, das Ding zur Kirche zu bringen; dort wird man entscheiden, was damit anzufangen ist.",
	"Danke fСЊr den guten Rat.",
	"Genau hier auf dem Tisch liegen ein paar Werkzeuge: eine LС†tlampe, eine MetallsРґge, ein DosenС†ffner und andere. Nehmen Sie die, und versuchen Sie sie selbst zu С†ffnen - und ich brauche kein Geld.",
	"Vielen Dank, ",
	"Sie haben das Richtige getan, mein Sohn. Wir wissen nicht, was sich darin befindet, aber es scheint so, dass wir morgen die Kirche neu weihen mСЊssen.",
	"Ich mС†chte gar nicht wissen, wo Sie das her haben. Im Namen des ErlС†sers vergebe ich Ihnen all Ihre SСЊnden! Gehe hin in Frieden.",
	"Danke, Vater.",
	"Raub, am hellerlichten Tag! Was zur HС†lle geht hier vor?! Lungerst hier rum, Kumpel...",
	"He, wonach suchst du da?! Hast du etwa vor, mich auszurauben? Nun, das bedeutet dein Ende!",
	"Wart mal, hast du da eben reingegriffen? Oh, du bist also ein Dieb! Betrachte dich als erledigt, BСЊrschchen...",
	"Teufel! Decksjunge! Vagabund! ",
	"?Ay caramba!",
	"Aaah, zur HС†lle!",
	"Oh KapitРґn, das ist nicht auf einmal passiert, sondern geht schon eine ganze Weile so. Wir, die HРґndler der Karibik, stehen kurz vor dem Ruin. Und alles nur wegen dieser verdammten 'Blue Bird' ...",
	"СЏBlue Bird'?",
	"Ja, diese Teufelsschebecke, das einzige Schiff dieses Typs hier - auf dem Meer gibt es kein Entkommen vor ihr. Sie plСЊndert nur die HРґndlerschiffe. GroРЇe Karavanen, die von MilitРґrschiffen bewacht werden, bleiben davon verschont.",
	"Und warum sagen Sie dann, dass die HРґndler vor dem Ruin stehen? SchlieРЇlich kommen die GСЊter hier mit diesen Karavanen an.",
	"Ja, das tun sie. Aber das Problem bei dieser Situation ist, dass es unrentabel fСЊr uns ist. Es ist besser, ein eigenes Slup oder eine Fleute zu haben, die Waren in der Alten Welt zu kaufen und sie selbst hierher zu befС†rdern. Das nenne ich Handel!   \nAber wenn wir die Waren von Transporteuren abkaufen, geht es nicht mehr um Gewinne, sondern nur noch ums Р¬berleben.",
	"Ich verstehe. Es werden also nur Ihre Schiffe von der Schebecke geplСЊndert ...",
	"Genau. Fast alle HРґndler haben ihre Schiffe verloren. Zum Teufel mit dieser 'Blue Bird'!",
	"Stimmt, das ist schlecht fСЊr Sie ... Nun, was wollen Sie von mir?",
	"Wir wollen, dass Sie diese graugeflСЊgelte Bisamratte vernichten, verdammt nochmal!",
	"Und was springt dabei fСЊr mich heraus?",
	"Ich werde von allen meinen Kollegen eine wСЊrdige Belohnung sammeln. Ich kann Ihnen 50000 Piaster fest versprechen. Diese teuflische Schebecke muss auf den Meeresgrund befС†rdert werden!",
	"FСЊr diesen Betrag mache ich noch nicht einmal einen Finger krumm, mein Freund. Suchen Sie sich einen anderen Dummen!",
	"Hm, ich bin an dieser Summe interessiert. Ich bin bereit, die Aufgabe anzunehmen. Was sind die Bedingungen fСЊr die DurchfСЊhrung?",
	"Sie haben keine zeitliche Begrenzung. Mir ist absolut klar, dass das ein schwieriges Unterfangen wird, verdammt! Um ehrlich zu sein, hatten wir bereits versucht, Auftragskiller anzusetzen, um den KapitРґn zu beseitigen. Aber ohne Erfolg ...",
	"Wirklich? KС†nnen Sie mir mehr Einzelheiten hierzu erzРґhlen?",
	"Nun, wir legten alle etwas Geld zusammen und heuerten jemanden an, der den KРґptn dieser Teufelsschebecke bei den Piraten finden sollte. Aber das brachte nichts; unser angeheuerter Freund durchkРґmmte sechs Monate lang die ganze Karibik, ohne etwas zu finden. WeiРЇ der Teufel, wo die ihren Unterschlupf haben und wie sie die Beute verkaufen ...",
	"In Ordnung, mein Freund, das ist doch schon einmal etwas. Und nun hС†ren Sie sich meine Bedingungen fСЊr die Abmachung an.",
	"HС†ren Sie gut zu, ",
	"Diese Abmachung ist zwischen Ihnen und mir. Wie Sie das Geld einsammeln, ist mir egal, aber erwРґhnen Sie kein Wort davon, dass ich darin verwickelt bin. Und noch etwas. Sie sagten, dass FAST alle HРґndler ihre Schiffe verloren haben. Was meinen Sie mit 'fast'?",
	"Ein HРґndler hat immer noch eine Fleute. Er hatte GlСЊck, da er dieser Teufelsschebecke noch nie begegnet ist. Er ist unsere einzige Hoffnung, sich hier einmal fest niederzulassen, und alle unsere MРґnner schulden ihm etwas. Wenn er uns in diesen schwierigen Zeiten nicht unterstСЊtzen wСЊrde, wРґren wir schon vor langem am Ende gewesen. Er hat noch nie abgelehnt, uns Geld zu leihen!",
	"Ich verstehe. Er ist schon fast ein Heiliger! Wie heiРЇt er denn?",
	"Pascal Vousier. Er hat einen Laden auf Bermuda in der Piratensiedlung. Nehmen Sie also den Auftrag an?",
	"Und nehmen Sie meine Bedingung zum Stillschweigen an?",
	"NatСЊrlich!",
	"Abgemacht. Ich fange heute noch mit meiner Suche an und hoffe, bald Erfolg zu haben.",
	"Ach, wenn Sie doch nur recht hРґtten! Nun gut, Sie kС†nnen anfangen. Ich hoffe sehr, dass alles so lРґuft, wie Sie gesagt haben.",
	"Das wird es, ohne Zweifel!",
	"Nun, das ist schade. Dann werden wir wohl woanders nach einem 'Dummen' suchen mСЊssen ...",
	"Mmh ...",
	"Hervorragende Neuigkeiten, das kann man wohl sagen! Endlich kС†nnen wir wieder in Ruhe Handel betreiben ... MС†chten Sie Ihr Geld sofort bekommen?",
	"Ja, das wРґre wohl am besten ...",
	"Hm, Moment ... So viel ich weiРЇ, konnten Sie die Schebecke einnehmen, haben sie aber nicht versenkt! Sie ist nun in Ihrem Besitz.",
	"Ja, das stimmt. Haben Sie damit ein Problem?",
	"Nein, kein Problem. Bitte nehmen Sie Ihre Belohnung.",
	"Danke, das wРґre erledigt. WСЊnsche Ihnen alles Gute ... Р¬brigens, mС†chten Sie wissen, wer hinter all dem gesteckt hat?",
	"Hm, das wРґre wirklich sehr interessant zu erfahren ...",
	"Es war der ach so 'heilige' HРґndler der Karibik - Pascal Vousier.",
	"Das kann nicht sein!",
	"Doch, kann es. Leider kann ich es Ihnen nicht beweisen, aber passen Sie auf, wer Ihnen Ihr eigenes Geld leiht.",
	"Hm, das muss alles СЊberprСЊft werden ... In Ordnung, danke fСЊr Ihre Arbeit und die Informationen.",
	"Nicht der Rede wert, ich wurde ja dafСЊr bezahlt. Leben Sie wohl.",
	"Das Problem liegt darin, dass dieses verdammte Schiff nun in Ihren HРґnden ist. Und auch Sie sind ein Pirat, nebenbei bemerkt! Wer wird Sie also davon abhalten, HРґndler auf die gleiche Weise auszurauben wie der vorherige Besitzer?",
	"Hm, das ist in der Tat eine interessante Frage ... Dennoch, ich habe Ihren Auftrag ausgefСЊhrt!",
	"Nein, das haben Sie nicht. Wir hatten vereinbart, die 'Blue Bird' zu versenken, nicht sie zu entern.",
	"Ah, das ist also Ihre Antwort! Nun gut, ich verstehe Sie ... Ich wСЊnsche Ihnen alles Gute, und richten Sie Ihren Kollegen einen innigen GruРЇ von mir aus.",
	"Das werde ich, ohne Zweifel! Leben Sie wohl, und halten Sie zukСЊnftig Ihr Wort komplett.",
	"NatСЊrlich. Ich werde Sie allerdings wieder sehen ...",
	"Schade. Nun, Sie sind nicht der Erste, der diesen Auftrag annimmt und nichts erreicht. Schlimm - wir mСЊssen weiterhin mit unserer Misere leben ...",
	"Ich hoffe, alles wird sich im Laufe der Zeit regeln ...",
	"Das stimmt. Wir leben hier im Р¬berfluss und glauben fest daran, dass sich die Welt nur um uns dreht. Aber nein, wir kommen ja aus dem Staub und werden wieder zu Staub   \nHeh, irgendwie kommt gerade meine lyrische Ader durch.",
	"Kann schon einmal passieren ... Leben Sie wohl.",
	"Oh, was fСЊr ein Bastard! Unsere Р”ngste haben sich also bewahrheitet",
	"Ich wСЊrde Sie ja in Ruhe lassen, wenn Sie mich nicht betrСЊgen wСЊrden!",
	"Ach verdammt! Wache, schnappt ihn Euch! Du kommst nicht weit, Bastard ...",
	"Ihr hРґttet mir mein Geld geben sollen, Schlaumeier! Machen wir mit der Behandlung weiter ...",
	"Seien Sie verflucht, Bastard! Oh, wie ich es bereue, mich auf Sie eingelassen zu haben! Bevor Sie im Spiel waren, hatte uns die 'Blue Bird' nie SO VIEL Р”rger bereitet!",
	"Meine Freunde, Ihr seid selbst daran Schuld. Ihr hРґttet Euch an unsere Abmachung halten sollen.",
	"Was fСЊr eine Abmachung - zwischen uns und Ihnen? Wir hatten uns streng daran gehalten! Sie haben sie gebrochen, indem Sie die Schebecke nicht versenkten!",
	"Mon cher, es gibt keinen Grund zu schreien. Das wirkt sich negativ auf die StimmbРґnder aus. Was wРґre bloРЇ, wenn Sie auf einmal nicht mehr sprechen kС†nnten? Wie auch immer, ich bin bereit, mit Ihnen zu reden, aber nur wenn Sie ruhig bleiben ...",
	"In Ordnung, aber Ruhe hat hiermit nichts zu tun. Sie waren es, der die Bedingungen unserer Abmachung gebrochen hat, nicht wir - das ist das Problem!",
	"Heh! Ihr HРґndler seid Meister in vertrackten VertrРґgen. Ich kenne Eure Tricks. Irgendwo ein Komma in den Text hinein, und schon ergibt alles einen anderen Sinn.",
	"Warum reden Sie von Kommas? Wir hatten eine mСЊndliche Vereinbarung.",
	"Nun, das war bildhaft gesprochen. Die Sache ist, dass Sie eine Gelegenheit gefunden haben, mir mein versprochenes Geld vorzuenthalten. Und ich bin nun mal ein Pirat und habe deshalb keine Zeit, mich mit den Doppeldeutigkeiten Ihrer Bedingungen herumzuschlagen.",
	"Was fСЊr Bedingungen?",
	"Bedingungen unserer Vereinbarung. Die 'Blue Bird' stellte fСЊr Sie ein Problem dar - ich habe es fСЊr Sie gelС†st. Wenn Sie mir mein Geld gegeben hРґtten, hРґtte ich Ihnen kein Haar gekrСЊmmt. Somit sind alle Ihre Probleme sozusagen auf Ihre 'Weisheit' zurСЊckzufСЊhren ...",
	"Na gut. Nehmen Sie Ihre 50000 und verschwinden Sie!",
	"Nicht so schnell, mon cher. Die Sache ist nun so, dass weitere Kosten angefallen sind, als ich versucht habe, Sie wieder zur Vernunft zu bringen. Und dann der ganze Stress, dem ich ausgesetzt war. Deshalb hat sich die Summe erhС†ht.",
	"Und, was ist die neue Summe? Sagen Sie schon.",
	"Das Vierfache. Geben Sie mir 200.000, und ich lasse Sie in Ruhe. Andernfalls werde ich Sie ruinieren. Und dann tС†ten. Zuerst Ihre Familie, und dann Sie ...",
	"Oh, Sie sind ein Teufel!",
	"Und dazu noch ein sehr, sehr wСЊtender ...",
	"Gut, gut. Hier ist Ihr Geld. Und jetzt gehen Sie! Lassen Sie uns in Ruhe!",
	"Garantiert. Jetzt, da ich meine volle Bezahlung erhalten habe, wird die 'Blue Bird' keine Bedrohung mehr fСЊr Sie darstellen. Leben Sie wohl, und viel GlСЊck bei Ihren geschРґftlichen Unternehmungen ...",
	"Ganz genau. Sie kС†nnen eine Million Piaster in einer Minute von mir bekommen, wenn ich die Zustimmung erhalte.",
	"Ich habe Ihnen bereits gesagt, ",
	", dass ich das Geld habe. Ich warte nur noch auf die Zustimmung zur Р¬berweisung.",
	"Keine Sorge, ich habe das Geld. Ich warte nur noch auf die Zustimmung zur Р¬berweisung.",
	"Hm, ich habe den Eindruck, dass Sie an diesem Geld СЊbermРґРЇig interessiert sind. Mein Ruf ist makellos, aus diesem Grund kann ich nur wiederholen, was ich bereits gesagt habe. Ich habe den Betrag auf Ihren Namen, und Sie werden das Geld erhalten, nachdem ich die Zustimmung zur Р¬berweisung erhalten habe.",
	"Ich verstehe, das ist in Ordnung. Ich habe erfahren, was ich will.",
	"Argh. Okay, ich verstehe.",
	"Ich auch, machen Sie sich nicht zu viele Sorgen.",
	"Ich verstehe ... Danke, ",
	"Ja ja, ich habe die Erlaubnis zur DurchfСЊhrung dieser Finanzoperation erhalten. Alles in Ordnung fСЊr den Erhalt, ",
	"Heh, sehr gut ...",
	"Vielleicht mС†chten Sie das Geld ja anlegen? Ich bin stets zu Ihren Diensten; mein Ruf ...",
	"Schon verstanden, danke. Ich denke darСЊber nach.",
	"Ah, hier sind Sie endlich ...",
	"Was ist los? Warum sind Sie noch nicht an Bord der Korvette? ... Und wo ist der Mechaniker?",
	"Ich weiРЇ nicht, wo er im Moment ist. Als ich auf 'San Gabriel' ankam, wurde er gerade von den MilizionРґren weggebracht. Offensichtlich wurde er festgenommen, und das kann nur der Admiral angeordnet haben.",
	"Ay caramba! Und was machen wir jetzt?",
	"Kommen wir nicht auch ohne den Mechaniker klar?",
	"Wir brauchen Vedeker. Wir kommen zwar an Bord der Korvette, aber wir kС†nnen Sie ohne Henrik nicht rauslassen.",
	"Dann mСЊssen wir zum Kaperer gehen und den Mechaniker befreien. Leider muss ich bei diesem Teil des Unterfangens passen - alleine der Blick des Admirals bereitet mir Angst ...",
	"Heh, das ist klar ... Gehen Sie auf das Schiff, und ich werde bald mit Vedeker nachkommen. Die anderen Mannschaftsmitglieder sind bereits dort.",
	"Wie Sie wСЊnschen, KapitРґn.",
	"Keine Angst, ohne mich dort zu sein. Das wird alles in Ordnung gehen.",
	"Ah, hier sind Sie endlich ...",
	"Was ist los? Warum sind Sie noch nicht an Bord der Korvette? ... Und wo ist der Mechaniker?",
	"Ich weiРЇ nicht, wo er im Moment ist. Als ich auf 'San Gabriel' ankam, wurde er gerade von den MilizionРґren weggebracht. Offensichtlich wurde er festgenommen, und das kann nur der Admiral angeordnet haben.",
	"Ay caramba! Und was machen wir jetzt?",
	"Kommen wir nicht auch ohne den Mechaniker klar?",
	"Wir brauchen Vedeker. Wir kommen zwar an Bord der Korvette, aber wir kС†nnen Sie ohne Henrik nicht rauslassen.",
	"Dann mСЊssen wir zum Kaperer gehen und den Mechaniker befreien. Leider wРґre ich als Frau keine groРЇe Hilfe dabei.",
	"Das ist klar ... Gehen Sie auf das Schiff, und ich werde bald mit Vedeker nachkommen. Die anderen Mannschaftsmitglieder sind bereits dort.",
	"Wie Sie wСЊnschen, KapitРґn.",
	"Keine Angst, ohne mich dort zu sein. Das wird alles in Ordnung gehen.",
	"hat zugestimmt",
	"hat zugestimmt",
	"hat zugestimmt",
	"hat zugestimmt",
};
