string DLG_TEXT_RUM [333] = {
	"Hum, je vois... D'autres nouvelles ?",
	"Merci. J'en ai terminР в„–.",
	"Bon vent.",
	"Ah, je comprends... Autre chose ?",
	"Merci. J'en ai terminР в„–.",
	"Bon vent.",
	" C'est Р В·a qui se passe...",
	" Cela pourrait vous amuser.",
	" Et vous, capitaine, avez-vous des nouvelles pour notre colonie ?",
	"Vous racontez des choses intР в„–ressantes, ",
	"Dites-m'en plus...",
	"C'est trР С‘s intР в„–ressant ! Oh, je voulais vous demander autre chose...",
	"Puis-je vous poser une autre question ?",
	"Il pourrait se passer tant de choses dans le monde qui nous entoure. J'ai bien peur de ne pas avoir de nouvelles. ",
	"Je suis un peu pressР в„– lР В°, alors Р В·a sera pour une prochaine fois.",
	" Il se passe pas grand-chose par ici. Mais s'il s'Р в„–tait passР в„– un truc inhabituel, tout le monde en parlerait.",
	" Donc rien de neuf pour l'instant. Mais peut-Р С”tre que ",
	" sait quelque chose ?",
	"Alors dites-moi tout...",
	"Vous ne savez rien du tout ! Bon, je voulais vous demander autre chose...",
	"Alors comme Р В·a, vous ne savez pas. TrР С‘s bien, alors dites-moi...",
	"Eh bien, vous ne m'avez pas",
	" Р в„–tР в„– d'une grande aide ",
	", mais vous savez peut-Р С”tre autre chose ?",
	"Je ne sais rien qui pourrait vous intР в„–resser.",
	"Je vous raconterai quelque chose avec plaisir, mais peut-Р С”tre une autre fois.",
	"Malheureusement, je ne sais rien de plus. Au revoir.",
	"Vous me fatiguez avec vos questions. Si vous voulez bien m'excuser, j'ai Р В° faire.",
	"Merci. J'en ai terminР в„–.",
	"Bon vent.",
	"Eh ben... Hic ! ",
	"HР в„–, l'est bon ce rhum ! ",
	"Bi-i-ien... ",
	"Pour Р В·a, je boirais encore un verre...",
	"TrР С‘s bien. C'est parti pour une autre tournР в„–e.",
	"Merci, mais je dois y aller.",
	"Houa, ce rhum a du mordant. J'adore Р С”tre mordu, ceci dit.",
	"Vous imaginez, je suis assis lР В°, j'embР С”te personne, et tout Р В° coup, ce mec, lР В°, Avery, me fonce dessus et me frappe en pleine tР С”te ! Et lР В° il me dit 'Tu dois de l'argent ?!' Puis il me dit que c'est une erreur. Une erreur qui m'a coРЎвЂ№tР в„– une dent ! Et vous allez pas me croire, mais Р В·a fait une semaine et j'ai toujours mal. Quelle souffrance ! Peut-Р С”tre qu'une petite choppe de biР С‘re...",
	"Hum, bien sРЎвЂ№r...",
	"Il y avait un gars assis en face de moi, il y a environ cinq jours, comme vous en ce moment. Il s'appelait, attendez un peu... John Avery. Il m'a expliquР в„– comment il avait arnaquР в„– le prР С”teur du coin, hР в„– hР в„– hР в„–. Р вЂ”a lui apprendra, Р В° ce sale vampire qui roule sous l'or alors que les honnР С”tes travailleurs n'ont rien Р В° se mettre sous la dent...",
	"Oh oui, ces prР С”teurs sont de vraies sangsues.",
	"Il y a eu un chouette combat ici il y a trois jours ! John Avery a Р в„–pinglР в„– un gars qui trichait aux cartes. Il faut dire qu'il sait se servir de son Р в„–pР в„–e ! Schling, schling, et adieu le tricheur. Р вЂ”a a mis une sacrР в„–e animation. Mais John est un type bien, il a payР в„– une tournР в„–e gР в„–nР в„–rale. Moi je dis chapeau !",
	"Oh, vraiment ? Classe...",
	" Oui. Je me souviens de rien d'autre.",
	" Et maintenant je dois retourner Р В° mes affaires.",
	"Je vous ai dР в„–jР В° dit que j'avais pas le temps de bavarder !",
	"Je suis quelqu'un de trР С‘s occupР в„– et j'ai pas le temps de ragoter !",
	"C'est trР С‘s intР в„–ressant ! Mais revenons Р В° nos moutons.",
	"Merci. Encore une chose...",
	"Les bras m'en tombent ! Vous mentez bien. Mais j'ai une autre question.",
	"Alors ne perdons pas plus de temps et revenons-en Р В° nos affaires.",
	" Une derniР С‘re chose et je m'en vais.",
	"Vous avez raison, le temps c'est de l'argent.",
	"Vous ne pensez qu'Р В° votre propre intР в„–rР С”t. Bon, du calme.",
	"Je vous prie de m'excuser. Revenons Р В° nos moutons.",
	"Р С’ des jours meilleurs, vieille branche.",
	"Tous mes vРЎС™ux, ",
	"Caramba ! Ne bougez pas d'un pouce. Je reviens.",
	"Р вЂ”a m'a fait plaisir de vous voir, ",
	" ! Prenez soin de vous !",
	"Bon vent !",
	"Au revoir, mon vieux.",
	"HР в„– ! Qu'est-ce que vous cachez ? Du rhum ? Non ?! Bon, alors je vais me chercher Р В° boire.",
	"Excusez-moi. J'ai une affaire urgente Р В° rР в„–gler dans la citР в„–.",
	"Ho. Ma foi, on se reverra.",
	"Je dois y aller. Au revoir, ",
	"Ne me rР в„–pondez pas ! J'ai pas le temps de discuter avec vous !",
	"Je ferais bien d'aller jeter un РЎС™il au vaisseau. Qui sait ce qui se passe quand je ne suis pas lР В°. Au revoir, ",
	"HР в„–, l'ami, Р В·a va ? C'est moi, ",
	" ! Laissez tomber. Je reviendrai plus tard.",
	"Votre foie vous aura emportР в„– avant que je revienne...",
	"Comptez vos piastres, vieux roublard ! Je reviendrai plus tard.",
	"Р вЂ”a m'a fait plaisir de vous voir, ",
	"C'est trР С‘s intР в„–ressant ! Oh, je voulais vous demander autre chose...",
	"Puis-je vous poser une autre question ?",
	"Merci. Avec respect... Au revoir.",
	"Au revoir.",
	"Les informations, Р В·a se paye. Pour la modique somme de 1000 piastres, je vous dirai ce que je sais.",
	"Bizarrement, je m'en souviens pas. Mais peut-Р С”tre que 1000 piastres me rafraР С•chiraient la mР в„–moire.",
	"Je veux bien vous dire tout ce que je sais. Mais pas gratuitement - 1000 piastres, pas un de moins.",
	"J'ai rien Р В° ajouter. Maintenant si vous voulez bien m'excuser, les affaires n'attendent pas.",
	"Payer pour du blabla inutile ? Non merci, Р В° d'autres.",
	"Pour une telle somme, je dР в„–couvrirai tout moi-mР С”me.",
	"Parlons d'autre chose.",
	"Vous lez aurez si vous me donnez de bons renseignements.",
	"Je paierai, mais seulement si vous me dites quelque chose de vraiment important.",
	"Je n'ai pas une telle somme.",
	"Des vaisseaux ont commencР в„– Р В° disparaР С•tre rР в„–cemment, mais le plus Р в„–trange, c'est que Р В·a ne concerne que des sloops et des lougres de transport. On dit qu'un brick serait apparu dans les eaux de CumanР В±... Alors soyez prudent !",
	"Que des lougres de transport, vous dites ? TrР С‘s intР в„–ressant... Est-ce que vous savez autre chose ?",
	"Je ne paie pas pour des ragots stupides, adieu.",
	"Vos informations ne valent pas un clou. Vous n'aurez rien.",
	"Je vous remercie, voilР В° votre argent. Est-ce que vous vous souvenez de quoi que ce soit d'autre ?",
	"Tenez, voilР В° votre argent, vous l'avez bien mР в„–ritР в„–. Autre chose ?",
	"Comprenez-moi, j'ai une famille Р В° nourrir.",
	"Parlons d'autre chose.",
	"Merci. J'en ai terminР в„–.",
	"Au revoir.",
	"Au revoir.",
	"Oui, c'est intР в„–ressant. J'ai une autre question...",
	"Hum, je voulais vous demander autre chose...",
	"Eh bien, adieu, spР в„–culateur.",
	"Au revoir, l'ami.",
	"J'ai plus rien Р В° dire. Je vous ai dit tout ce que je savais.",
	"Je connais pas d'autres rumeurs, dР в„–solР в„–...",
	"Je comprends. Alors, au revoir.",
	"Je vois. Bien, au revoir, l'ami...",
	"Oui, c'est intР в„–ressant. J'ai une autre question...",
	"Hum, je voulais vous demander autre chose...",
	"Eh bien, adieu, spР в„–culateur.",
	"Au revoir, l'ami.",
	"J'ai plus rien Р В° dire. Je vous ai dit tout ce que je savais.",
	"Je connais pas d'autres rumeurs, dР в„–solР в„–...",
	"Je comprends. Alors, au revoir.",
	"Je vois. Bien, au revoir, l'ami...",
	"Compris...",
	"Soit.",
	"J'ai plus rien Р В° dire. Je vous ai dit tout ce que je savais.",
	"Je ne sais rien de plus, dР в„–solР в„–...",
	"DР в„–solР в„–, mais je vous ai dР в„–jР В° tout dit.",
	"Je connais pas d'autres rumeurs, dР в„–solР в„–...",
	"Compris.",
	"Bien, au revoir.",
	"Argent ? Hum, allez-y, je vous Р в„–coute.",
	"Les histoires d'argent sont toujours intР в„–ressantes. Parlez, je vous Р в„–coute.",
	"Bien, parlons argent.",
	"Vous Р С”tes sРЎвЂ№r que vous vous adressez Р В° la bonne personne, ",
	" ? Mon nom est ",
	". Qu'est-ce que je peux faire pour vous ?",
	"Vous voulez me parler d'argent, ",
	" ?! Je suis ",
	". Alors, qu'est-ce que vous me voulez ?",
	"Je vous Р в„–coute, ",
	" ? Vous voulez quelque chose ? Oh, pardon. Mon nom est ",
	"Le prР С”teur m'envoie rР в„–cupР в„–rer sa dette ! Par ici la monnaie !",
	"J'ai une question dР в„–licate Р В° propos de votre dette, ",
	"J'ai ramenР в„– votre crР в„–dit.",
	"Hum, j'ai dРЎвЂ№ faire erreur. Je n'ai aucune affaire d'ordre financier avec vous.",
	"Excusez-moi, je n'ai pas de question financiР С‘re pour vous.",
	"Oui, en effet. J'allais justement lui rembourser la totalitР в„–.",
	"Ah, c'est parfait ! Dans ce cas, vous devez me donner ",
	"Excellent, alors prenez la somme et rapportez-la vous-mР С”me !",
	"Non ! Je ne vous donnerai rien ! Et si vous insistez, j'appelle les gardes !",
	"Peu importe, vous devez me donner ",
	". Sinon je vais devoir employer la maniР С‘re forte.",
	"Exact !",
	"Malheureusement, je n'ai pas toute la somme.",
	"Peu importe, vous devez me donner ",
	". Sinon je vais devoir employer la maniР С‘re forte.",
	"Et combien vous avez ?",
	"VoilР В° la somme.",
	"Merci pour votre coopР в„–ration !",
	"Vous avez 30 jours pour vous prР в„–senter devant le patron avec la somme que vous lui devez.",
	"Content qu'on soit tombР в„–s d'accord.",
	"Ah, du balai !",
	"Vous avez 30 jours pour expliquer au patron l'Р в„–chec de la mission.",
	"Gardes ! Des voyous me cherchent des noises !",
	"Silence !",
	"Vous avez 30 jours pour expliquer au patron l'Р в„–chec de la mission.",
	"Seulement ",
	" piastres.",
	"Non. Je veux la totalitР в„– de la somme !",
	"Donnez-moi ce que vous avez, je paierai le reste. Je suis d'humeur gР в„–nР в„–reuse aujourd'hui.",
	"Vous Р С”tes bien aimable ! Merci beaucoup.",
	"Oh, pourquoi est-ce que je me mets toujours dans des situations pareilles ?",
	"Vous avez 30 jours pour vous prР в„–senter devant le patron avec la somme que vous lui devez.",
	"Tout Р В·a est trР С‘s bien, et j'accepte cet or. Cependant, vous n'avez pas respectР в„– le dР в„–lai convenu. Je me vois donc dans l'obligation de rР в„–duire votre rР в„–compense de ",
	"%. Je suis dР в„–solР в„–, mais c'est Р В° prendre ou Р В° laisser...",
	"Merci !",
	"Excellent ! J'attendais Р В·a depuis bien longtemps. VoilР В° votre rР в„–compense.",
	"Merci !",
	"Excellent ! Mais oРЎвЂ° sont les coffres remplis d'or ?",
	"Est-ce que vous accepterez l'or sans les coffres ?",
	"Je reviendrai plus tard.",
	"Non ! Uniquement dans des coffres !",
	"C'est bР С”te. Les rats ont souillР в„– les miens.",
	"Est-ce qu'une somme de, disons, ",
	" couvrirait le coРЎвЂ№t des coffres ?",
	"Oui, c'est acceptable.",
	"Alors marchР в„– conclu !",
	"Sauf que c'est trop pour moi.",
	"C'est un plaisir de faire affaire avec vous !",
	"Merci !",
	"Bon, alors. J'ai prР в„–parР в„– un paquet pour vous, que vous devez remettre en main propre Р В° quelqu'un de trР С‘s connu. Tenez, prenez !\nNe m'approchez plus et ne me parlez plus, Р В·a pourrait Р в„–veiller les soupР В·ons. Soyez prudent... ",
	"Hum, parfait. Je vous confie le paquet, et souvenez-vous qu'il doit Р С”tre remis en main propre Р В° son destinataire\nPartez Р В° prР в„–sent, et ne vous approchez plus de moi, c'est dangereux.",
	"Entendu. Adieu...",
	"Adieu, et bonne chance.",
	"HР в„–, est-ce que vous avez trouvР в„– la poudre de momie que je vous avais demandР в„–e ?",
	"Non, pas encore... Apparemment, certains vendeurs dans les rues en ont, mais ils s'en cachent...",
	"Non, pas encore... Mais je vais continuer mes recherches.",
	"HР в„–, est-ce que vous avez trouvР в„– la poudre de momie que je vous avais demandР в„–e ?",
	"Oui, j'en ai trouvР в„–. Combien vous m'en donnez ?",
	"Rien. Mais je connais quelqu'un qui vous en achР С‘tera.",
	"Hum, j'espР в„–rais recevoir l'argent tout de suite.",
	"Croyez-moi, vous n'y perdrez pas au change. Р в„ўcoutez-moi bien !\n",
	"En Guadeloupe, dans la citР в„– de Basse-Terre, habite un type bizarre appelР в„– Askold.",
	"DrРЎвЂћle de nom...",
	"Je le connais, j'ai pu lui parler. C'est un gars qui manque pas de culot...",
	"Alors ? Vous avez fait connaissance de sa mauvaise humeur ?",
	"Oh oui, il m'a sorti Р В° coups de pied comme un vaurien !",
	"Askold est un peu bourru, mais c'est un brave gars, et honnР С”te qui plus est. D'aprР С‘s les rumeurs, il paraР С•t qu'il est moscovite, qu'il vient de cet endroit au nord de l'Ancien Monde oРЎвЂ° il neige toute l'annР в„–e et oРЎвЂ° il n'y a que des ours et des forР С”ts Р В° perte de vue. C'est pour Р В·a qu'il est si sР в„–vР С‘re et qu'il est fort comme quatre\n",
	"Je sais pas trop comment ni quand il est arrivР в„– ici, et j'ai aucune idР в„–e de ce qu'il y fait\n",
	"Mais comme j'ai quelques affaires en cours avec lui, il me fait confiance\n",
	"Alors allez le voir, prР в„–sentez-vous, dites-lui que c'est moi qui vous envoie et tout se passera bien. Il vous achР С‘tera votre camelote puisque ce sont ses ordres.",
	"Et qu'est-ce que vous y gagnez, vous ?",
	"Vous inquiР в„–tez pas pour moi, je retiendrai une petite commission lors de notre prochain rР С‘glement de comptes.",
	"Je vois. Bien, j'irai peut-Р С”tre voir ce fameux Askold Р В° l'occasion.",
	"Peut-Р С”tre Р В° cause de l'inquisition ?",
	"Р вЂ”a m'en a tout l'air...",
	"Eh bien, vous vous attendiez Р В° quoi ? Laissez-moi vous dire une bonne chose, l'ami, ils ont de la poudre. Pas tous, bien sРЎвЂ№r, mais il y a en sРЎвЂ№rement quelques-uns qui en ont. Il vous suffit d'insister un peu plus, et vous obtiendrez ce que vous voudrez. ",
	"Eh bien, merci pour votre aide.",
	"Voyons voir cette boР С•te en fer. HР в„–, regardez-moi Р В·a, il y a des signes Р в„–tranges gravР в„–s dessus, c'est probablement de la sorcellerie. Je vous conseille d'amener Р В·a Р В° l'Р в„–glise, ils sauront quoi en faire.",
	"Merci pour le conseil.",
	"Juste lР В°, sur la table, il y a des outils : chalumeau, scie Р В° mР в„–taux, pinces, etc. Prenez-les et ouvrez-la vous-mР С”me. Et je ne veux pas d'argent.",
	"Merci, ",
	"Vous avez fait ce qu'il fallait, mon fils. On ne sait pas ce qu'il y a Р В° l'intР в„–rieur, mais on dirait que demain nous allons devoir consacrer l'Р в„–glise Р В° nouveau\n",
	"Je ne veux pas savoir oРЎвЂ° vous avez trouvР в„– Р В·a. Au nom du Seigneur, je vous pardonne tous vos pР в„–chР в„–s ! Allez en paix.",
	"Merci, mon pР С‘re.",
	"Un cambriolage, en plein jour ! Mais qu'est-ce qui se passe ? Restez lР В°, mon ami...",
	"HР в„–, qu'est-ce que vous faites lР В° ?! Vous ne pensez pas me voler ? Dans ce cas, c'en est terminР в„– pour vous !",
	"Attendez, vous faites quoi ? Hum, vous m'avez tout l'air d'Р С”tre un voleur ! Vous Р С”tes fini, mon ami...",
	"Diable !",
	"Caramba !",
	"Ah, fichtre !",
	"Oh, capitaine, Р В·a ne s'est pas passР в„–, mais Р В·a se passe depuis longtemps maintenant. Nous autres marchands des CaraР С—bes, on court Р В° notre perte. Tout Р В·a Р В° cause de ce satanР в„– 'Oiseau bleu'...",
	"РЎРЏOiseau bleu' ?",
	"Oui, ce maudit chebec, le seul vaisseau de ce type ici, impossible de lui Р в„–chapper. II ne pille que les vaisseaux marchands. Il ne s'attaque pas aux grands convois escortР в„–s par des navires militaires.",
	"Alors pourquoi dites-vous que les marchands courent Р В° leur perte ? Au final, les marchandises sont quand mР С”me acheminР в„–es par les convois.",
	"Certes, mais le problР С‘me c'est que cette situation n'est pas profitable. Il vaut mieux avoir son propre sloop ou sa propre flРЎвЂ№te, acheter sa marchandise dans l'Ancien Monde et la ramener ici soi-mР С”me. Р вЂ”a, c'est ce que j'appelle du commerce\nMais acheter des marchandises livrР в„–es par transporteurs, c'est pas du profit, c'est de la survie. ",
	"Je vois. Alors comme Р В·a, ce chebec ne pille que vos vaisseaux...",
	"Exactement. Presque tous les marchands ont dР в„–jР В° perdu leurs vaisseaux. Maudit soit cet 'Oiseau bleu' !",
	"Je suis dР в„–solР в„– pour vous... Alors, qu'est-ce que vous attendez de moi ?",
	"On veut que vous nous dР в„–barrassiez de cet empР С”cheur de commercer en rond !",
	"Et qu'est-ce que j'y gagne ?",
	"On va se cotiser avec les collР С‘gues pour rassembler une belle somme. Je peux vous promettre 50000 piastres. Ce fichu chebec doit rejoindre le fond de l'ocР в„–an !",
	"Je ne lР С‘verai mР С”me pas le petit doigt pour une telle somme, l'ami. Trouvez un autre pigeon !",
	"Hum, votre offre m'intР в„–resse. Je suis prР С”t Р В° accepter cette mission. Quelles sont les conditions ?",
	"Vous n'avez pas de limite de temps. Je comprends parfaitement que ce ne sera pas facile ! Pour vous dire la vР в„–ritР в„–, on a dР в„–jР В° essayР в„– de payer des assassins, on voulait se dР в„–barrasser du capitaine. Sans rР в„–sultats !",
	"Vraiment ? Est-ce que vous pouvez m'en dire plus Р В° ce sujet ?",
	"Eh bien, on s'est tous cotisР в„–s et on a engagР в„– quelqu'un pour trouver le capitaine de ce chebec parmi les pirates. Mais Р В·a n'a pas marchР в„–, notre gars a Р в„–cumР в„– les CaraР С—bes pendant six mois, mais n'a rien trouvР в„–. Dieu seul sait oРЎвЂ° ils se cachent et comment ils revendent leur butin...",
	"TrР С‘s bien, l'ami, c'est toujours bon Р В° savoir. Maintenant, voici mes conditions.",
	"Je suis tout ouР С—e, ",
	"Ce marchР в„– doit rester entre nous. Rassemblez l'argent comme vous pouvez, mais ne dites Р В° personne que je suis impliquР в„–. Autre chose, vous avez dit que PRESQUE tous les marchands avaient perdu leurs vaisseaux. Р вЂ”a veut dire quoi 'presque' ?",
	"Il y en a un qui a encore une flРЎвЂ№te. Mais il a de la chance, il n'est jamais tombР в„– sur ce chebec. Il est notre seul espoir de prospР в„–rer ici, les nРЎвЂћtres lui doivent beaucoup. Sans son soutien, on aurait tous fait faillite il y a longtemps. Il ne refuse jamais de nous prР С”ter un peu d'argent !",
	"Je vois. C'est un saint homme ! Comment s'appelle-t-il ?",
	"Pascal Vousier. Il tient un magasin dans la colonie pirate des Bermudes. Alors, vous acceptez le travail ?",
	"Est-ce que vous acceptez de garder le silence ?",
	"Bien sРЎвЂ№r !",
	"Alors c'est d'accord. Je m'y mets dР С‘s aujourd'hui, et j'espР С‘re en finir rapidement.",
	"Oh, si seulement vous aviez raison ! TrР С‘s bien, soit. J'espР С‘re vraiment que tout se passera comme vous dites.",
	"Mais oui, ne vous en faites pas !",
	"Eh bien, c'est dommage. Nous allons devoir trouver 'un autre pigeon' ailleurs...",
	"Hum...",
	"Excellente nouvelle ! On va enfin pouvoir reprendre les affaires... Vous voulez votre argent tout de suite ?",
	"Oui, je prР в„–fР в„–rerais...",
	"Hum, attendez... D'aprР С‘s ce que je sais, vous avez abordР в„– le chebec mais ne l'avez pas coulР в„– ! Il est maintenant en votre possession.",
	"En effet. OРЎвЂ° est le problР С‘me ?",
	"Aucun problР С‘me, voici votre rР в„–compense.",
	"Merci, c'est rР в„–glР в„–. Je vous souhaite bonne chance... Au fait, vous voulez savoir qui Р в„–tait derriР С‘re tout Р В·a ?",
	"Hum, je suis curieux de le savoir...",
	"C'Р в„–tait le 'vР в„–nР в„–rable' marchand des CaraР С—bes - Pascal Vousier.",
	"C'est impossible !",
	"Et pourtant. Malheureusement, je n'ai aucune preuve, mais rappelez-vous qu'il vous prР С”te votre propre argent.",
	"Hum, tout Р В·a mР в„–rite vР в„–rification... Eh bien, merci pour le travail accompli et pour cette information.",
	"De rien, vous avez payР в„– pour Р В·a. Adieu.",
	"Le problР С‘me c'est que ce maudit vaisseau est entre vos mains et que vous Р С”tes un pirate, vous aussi ! Qui me dit que vous n'allez pas piller les marchands comme le faisait son prР в„–cР в„–dent propriР в„–taire ?",
	"Hum, c'est une question intР в„–ressante... Cela dit, j'ai rempli ma part du marchР в„– !",
	"C'est faux. Vous deviez couler l'Oiseau bleu, pas l'aborder.",
	"Ah, alors c'est Р В·a votre rР в„–ponse ! Bon, j'ai compris... Bon vent Р В° vous, et transmettez mes amitiР в„–s Р В° vos collР С‘gues.",
	"Je n'y manquerai pas ! Adieu, et tР Р†chez de tenir entiР С‘rement parole dorР в„–navant.",
	"Bien sРЎвЂ№r. Mais on se reverra...",
	"Quel dommage. Ma foi, vous n'Р С”tes pas le premier Р В° accepter ce travail et Р В° Р в„–chouer. Tant pis, on va devoir continuer Р В° vivre dans la misР С‘re...",
	"J'espР С‘re que tout finira par s'arranger...",
	"C'est vrai. On vit ici dans la vanitР в„– en croyant que le monde tourne autour de nous. Mais non, de la terre nous venons et Р В° la terre nous retournerons\nBah, voilР В° que je fais de la poР в„–sie maintenant...",
	"Р вЂ”a arrive... Eh bien, adieu.",
	"Oh, espР С‘ce d'enflure ! Alors nos craintes Р в„–taient justifiР в„–es !",
	"Je vous aurais laissР в„– tranquilles si vous ne m'aviez pas arnaquР в„– !",
	"Gardes, saisissez-le ! Vous n'irez pas loin, raclure...",
	"Vous auriez dРЎвЂ№ me donner mon argent, vieille fouine. Continuons ton traitement...",
	"Soyez maudit, racaille ! Je n'aurais jamais dРЎвЂ№ traiter avec vous ! Avant votre arrivР в„–e, l'Oiseau bleu ne nous avait jamais causР в„– AUTANT de problР С‘mes !",
	"Vous ne pouvez vous en prendre qu'Р В° vous-mР С”me, vous auriez dРЎвЂ№ remplir votre part du marchР в„–.",
	"Quoi, le marchР в„– entre vous et nous ? On s'y est tenu Р В° la lettre ! C'est vous qui ne l'avez pas respectР в„– en ne coulant pas le chebec !",
	"Inutile de crier, mon cher, c'est mauvais pour les cordes vocales. Vous risqueriez de perdre votre voix. Quoi qu'il en soit, je suis prР С”t Р В° discuter, mais uniquement si vous gardez votre calme...",
	"TrР С‘s bien, mais le fait que je sois calme ou pas n'a rien Р В° voir lР В°-dedans. C'est vous qui avez enfreint les termes de notre accord, pas nous !",
	"Pfff ! Je vous connais, vous les marchands. Vous Р С”tes les spР в„–cialistes des contrats douteux. Il suffit de rajouter une virgule pour que le sens change du tout au tout.",
	"Qu'est-ce que vous racontez avec vos virgules ? On avait un accord oral.",
	"C'Р в„–tait une faР В·on de parler. Le fait est que vous avez eu l'opportunitР в„– de garder l'argent et que vous l'avez saisie. Je suis un pirate, moi, j'ai pas le temps de dР в„–chiffrer les double-sens de vos conditions.",
	"Quelles conditions ?",
	"Les conditions de notre accord. L'Oiseau bleu Р в„–tait un problР С‘me pour vous, j'ai rР в„–solu ce problР С‘me. Si vous m'aviez donnР в„– mon argent, je ne vous aurais fait aucun mal. VoilР В° ce qui arrive quand on veut jouer au plus malin...",
	"TrР С‘s bien, prenez vos 50000 piastres et fichez le camp !",
	"Pas si vite, mon cher. J'ai dРЎвЂ№ faire quelques dР в„–penses imprР в„–vues dans le but de vous faire entendre raison. Sans parler du stress auquel j'ai Р в„–tР в„– soumis. La somme a donc augmentР в„–.",
	"Et Р В° combien s'Р в„–lР С‘ve cette somme ? Allez-y, parlez.",
	"Elle a Р в„–tР в„– multipliР в„–e par quatre. 200000 piastres et je vous laisse tranquilles. Sinon, je vous tue. D'abord vos familles, puis vous...",
	"Vous Р С”tes un dР в„–mon !",
	"Et trР С‘s en colР С‘re, avec Р В·a...",
	"TrР С‘s bien. VoilР В° votre argent. Disparaissez Р В° prР в„–sent ! Et laissez-nous en paix !",
	"Avec plaisir. Maintenant que vous m'avez payР в„–, l'Oiseau bleu ne sera plus une menace pour vous. Adieu, et bonne chance pour vos affaires commerciales...",
	"Tout Р В° fait. Vous pouvez obtenir 1000000 de piastres dР С‘s que je reР В·ois la confirmation.",
	"Je vous ai dР в„–jР В° dit, ",
	", que j'avais l'acompte. J'attends la confirmation pour le transfР в„–rer.",
	"Inutile de vous en faire. J'ai l'acompte. J'attends la confirmation pour le transfР в„–rer.",
	"Hum, on dirait que vous vous intР в„–ressez de trР С‘s prР С‘s Р В° cet acompte. Ma rР в„–putation est sans faille, alors je ne peux que me rР в„–pР в„–ter une fois de plus. J'ai l'acompte Р В° votre nom, et vous le recevrez dР С‘s que j'aurai eu la confirmation pour le transfР в„–rer.",
	"Entendu. C'est parfait. J'ai appris ce que je voulais savoir.",
	"D'accord, je comprends !",
	"Moi aussi, ne vous inquiР в„–tez pas.",
	"Je comprends... Merci, ",
	"Oui, oui, j'ai reР В·u la permission d'effectuer cette opР в„–ration financiР С‘re. Bon pour recevoir, ",
	"Ah, trР С‘s bien...",
	"Peut-Р С”tre souhaitez-vous faire fructifier cet argent ? Je suis Р В° votre service, ma rР в„–putation...",
	"J'ai compris, merci. Je vais y rР в„–flР в„–chir.",
	"Ah, vous voilР В° enfin...",
	"Quel est le problР С‘me ? Pourquoi vous n'Р С”tes pas encore Р В° bord de la corvette ? Et oРЎвЂ° est le mР в„–canicien ?",
	"Je ne sais pas oРЎвЂ° il est en ce moment. Quand je suis arrivР в„– sur le 'San Gabriel', il se faisait emmener par les hommes de la milice. Apparemment, il s'est fait arrР С”ter. Seul l'amiral a pu faire Р В·a.",
	"Caramba ! Qu'est-ce qu'on fait maintenant ?",
	"On ne peut pas se passer de mР в„–canicien ?",
	"On a besoin de Vedeker. On peut monter Р В° bord de la corvette, mais on ne pourra pas la dР в„–gager sans Henrik.",
	"Dans ce cas, on doit aller dans la rР в„–sidence et libР в„–rer le mР в„–canicien. Malheureusement, je vais devoir dР в„–cliner, rien que de voir le regard de l'amiral, je suis terrifiР в„–...",
	"Ouais, Р В·a se voit... Montez Р В° bord, je reviens bientРЎвЂћt avec Vedeker. Apparemment, les autres membres de l'Р в„–quipage sont dР в„–jР В° lР В°.",
	"Р С’ vos ordres, capitaine.",
	"Ne paniquez pas en mon absence. Tout ira bien.",
	"Ah, vous voilР В° enfin...",
	"Quel est le problР С‘me ? Pourquoi vous n'Р С”tes pas encore Р В° bord de la corvette ? Et oРЎвЂ° est le mР в„–canicien ?",
	"Je ne sais pas oРЎвЂ° il est en ce moment. Quand je suis arrivР в„–e sur le 'San Gabriel', il se faisait emmener par les hommes de la milice. Apparemment, il s'est fait arrР С”ter. Seul l'amiral a pu faire Р В·a.",
	"Caramba ! Qu'est-ce qu'on fait maintenant ?",
	"On ne peut pas se passer de mР в„–canicien ?",
	"On a besoin de Vedeker. On peut monter Р В° bord de la corvette, mais on ne pourra pas la dР в„–gager sans Henrik.",
	"Dans ce cas, on doit aller dans la rР в„–sidence et libР в„–rer le mР в„–canicien. Malheureusement, en tant que femme, je ne peux pas vous aider.",
	"C'est clair... Montez Р В° bord, je reviens bientРЎвЂћt avec Vedeker. Apparemment, les autres membres de l'Р в„–quipage sont dР в„–jР В° lР В°.",
	"Р С’ vos ordres, capitaine.",
	"Ne paniquez pas en mon absence. Tout ira bien.",
	"a acceptР в„–",
	"a acceptР в„–",
	"a acceptР в„–",
	"a acceptР в„–",
};
